---
abstract: 'class for searching www.lycos.com'
author:
  - 'Martin Thurn <mthurn@cpan.org>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: WWW::Search::Lycos
name: WWW-Search-Lycos
no_index:
  directory:
    - inc
    - t
requires:
  HTML::TreeBuilder: 0
  WWW::Search::Test: 2.21
  perl: 5.004
resources:
  license: http://dev.perl.org/licenses/
version: 2.223
